#!/usr/bin/perl -w

use Test::Harness;
use Getopt::Long;

my %Opts;
GetOptions(\%Opts, "aegis_output=s");
die "Usage: runtests --aegis_output=\${Output} \${File_Name}\n"
  unless $Opts{aegis_output};

my $strap = Test::Harness::Straps::Aegis->new;
$strap->{callback} = $Test::Harness::Strap->{callback};
$Test::Harness::Strap = $strap;

open AEGIS_OUT, ">$Opts{aegis_output}" or 
    die "Can't open $Opts{aegis_output}: $!";
print AEGIS_OUT <<"END";
test_result = [
END

runtests @ARGV;

print AEGIS_OUT <<"END";
];
END


package Test::Harness::Straps::Aegis;

use base 'Test::Harness::Straps';

sub analyze_file {
    my $self = shift;
    my $file = $_[0];

    my %results = $self->SUPER::analyze_file(@_);

    print ::AEGIS_OUT <<"END";
    {
        file_name       = "$file";
        exit_status     = $results{exit};
    },
END

    return %results;
}
