name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:

  ubuntu:
    name: "quick test"
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1
      PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - run: perl -V
      - name: Install Dependencies
        run: cpm install -g --show-build-log-on-failure --cpanfile cpanfile
      - run: perl Makefile.PL
      - run: make
      - run: make test

  perl-versions:
    runs-on: ubuntu-latest
    name: List Perl versions
    outputs:
      perl-versions: ${{ steps.action.outputs.perl-versions }}
    steps:
      - id: action
        uses: perl-actions/perl-versions@v2
        with:
          since-perl: v5.8
          with-devel: true

  perl:
    name: "Perl v${{ matrix.perl-version }}"
    needs: [ubuntu, perl-versions]
    runs-on: ubuntu-latest

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1
      PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson(needs.perl-versions.outputs.perl-versions) }}

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v6
      - run: perl -V
      - name: Install Dependencies
        run: cpm install -g --show-build-log-on-failure --cpanfile cpanfile
      - run: perl Makefile.PL
      - run: make
      - run: make test
