name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl-versions:
    runs-on: ubuntu-latest
    name: List perl versions
    outputs:
      perl-versions:  ${{ steps.action.outputs.perl-versions }}
    steps:
      - id:           action
        uses:         perl-actions/perl-versions@v2
        with:
          since-perl: v5.8
          target:     perl-tester

  perl:
    needs:
      - perl-versions

    runs-on: ubuntu-latest

    env:
       PERL_USE_UNSAFE_INC: 0
       AUTHOR_TESTING: 1
       AUTOMATED_TESTING: 1
       RELEASE_TESTING: 1
       PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson (needs.perl-versions.outputs.perl-versions) }}

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Install Dependencies CI
        run: cpm install -g --show-build-log-on-failure --cpanfile cpanfile
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: make
        run: make
      - name: Run Tests
        run: make test
